spring:
  datasource:
    url: jdbc:mysql://ecommerce-db.cjrba3xiwusx.ap-south-1.rds.amazonaws.com/ecommercedb
    username: dbadmin
    password: dbpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
